# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfc < Formula
  desc "CLI for HCP Terraform"
  homepage "https://github.com/justinclayton/tfc-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justinclayton/tfc-cli/releases/download/v0.1.0/tfc_0.1.0_darwin_amd64.tar.gz"
      sha256 "5eda94b7ed19318a95bf82ece86e1fe2cfd1949eb19e9c1161525b957482e4a1"

      define_method(:install) do
        bin.install "tfc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justinclayton/tfc-cli/releases/download/v0.1.0/tfc_0.1.0_darwin_arm64.tar.gz"
      sha256 "59c7d50092c7f6029c76cc5d006389ba836f865f124b8942e85d4743dcfc8ffd"

      define_method(:install) do
        bin.install "tfc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinclayton/tfc-cli/releases/download/v0.1.0/tfc_0.1.0_linux_amd64.tar.gz"
      sha256 "40396e873f1f558a43e4f29917836986228f754d8986407a5305b71ebac1bb33"
      define_method(:install) do
        bin.install "tfc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinclayton/tfc-cli/releases/download/v0.1.0/tfc_0.1.0_linux_arm64.tar.gz"
      sha256 "4a24c421ee340e2c85fbbf0277b33c91f37b83e09e4da50d22a707c0c1777434"
      define_method(:install) do
        bin.install "tfc"
      end
    end
  end

  test do
    system "#{bin}/tfc", "--version"
  end
end
