# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfc < Formula
  desc "CLI for HCP Terraform"
  homepage "https://github.com/justinclayton/tfc-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justinclayton/tfc-cli/releases/download/v0.2.0/tfc_0.2.0_darwin_amd64.tar.gz"
      sha256 "ec1c2a9d1774ba20138f5c1d5713eb98f11453be308b8509237372b91e203cbd"

      define_method(:install) do
        bin.install "tfc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justinclayton/tfc-cli/releases/download/v0.2.0/tfc_0.2.0_darwin_arm64.tar.gz"
      sha256 "35ff4d73977b748e907fa83ed4f9bd05b5bbf4b4c5b17497d84a45afcbe023d3"

      define_method(:install) do
        bin.install "tfc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinclayton/tfc-cli/releases/download/v0.2.0/tfc_0.2.0_linux_amd64.tar.gz"
      sha256 "38b008bab2fa750c18006ff6e40f59549ffd15e789c563372c72ed38f5523df3"
      define_method(:install) do
        bin.install "tfc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinclayton/tfc-cli/releases/download/v0.2.0/tfc_0.2.0_linux_arm64.tar.gz"
      sha256 "0f60d8b26825a80cc3484994c2fac1d337d06f811e93ebe038fb83c1a7a8089a"
      define_method(:install) do
        bin.install "tfc"
      end
    end
  end

  test do
    system "#{bin}/tfc", "--version"
  end
end
